const mongoose = require("mongoose");

const defaultImageURL =
  "https://img.freepik.com/free-vector/image-folder-concept-illustration_114360-114.jpg?t=st=1699951857~exp=1699952457~hmac=826e3d9034be16eefac62f009b9437a6e0a5a5d0a02cfa60bd197839a6a7fdd0";

const ApplicationSchema = new mongoose.Schema({
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User",
    required: true,
  },
  completed_application: {
    type: Boolean,
    default: false,
  },
  application_number: String,
  application_status: { type: String, default: "Under Review" },

  study_country: { type: String, default: null },
  program_of_study: { type: String, default: null },
  course_of_study: { type: String, default: null },
  paid_fee: { type: String, default: null },
  fee_price: { type: String, default: null },
  fee_date: { type: String, default: null },
  fee_name: { type: String, default: null },
  admission_processing_fee: { type: String },
  has_paid_fee: {
    type: Boolean,
    default: false,
  },

  firstname: { type: String, default: "nil" },
  lastname: { type: String, default: "nil" },
  middlename: { type: String, default: "nil" },
  dob: { type: String, default: "nil" },
  first_language: { type: String, default: "nil" },
  country_of_citizenship: { type: String, default: "nil" },
  i_p_id: { type: String, default: "nil" },
  i_p_issue_date: { type: String, default: "nil" },
  i_p_expiry_date: { type: String, default: "nil" },
  i_p_issue_auth: { type: String, default: "nil" },
  gender: { type: String, default: "nil" },
  marital_status: { type: String, default: "nil" },
  state: { type: String, default: "nil" },
  address: { type: String, default: "nil" },
  email: { type: String, default: "nil" },
  phone: { type: String, default: "nil" },
  academic_c: { type: String, default: "nil" },
  date_h_e_a: { type: String, default: "nil" },
  class_award: { type: String, default: "nil" },
  cgpa: { type: String, default: "nil" },
  e_firstname: { type: String, default: "nil" },
  e_lastname: { type: String, default: "nil" },
  e_middlename: { type: String, default: "nil" },
  e_email: { type: String, default: "nil" },
  e_address: { type: String, default: "nil" },
  e_phone: { type: String, default: "nil" },
  e_relationship: { type: String, default: "nil" },

  english_test: { type: String, default: "nil" },
  english_score: { type: String, default: "nil" },
  english_date: { type: String, default: "nil" },
  other_language: { type: String, default: "nil" },
  other_language_score: { type: String, default: "nil" },
  other_language_date: { type: String, default: "nil" },
  other_exam: { type: String, default: "nil" },
  other_exam_score: { type: String, default: "nil" },
  other_exam_date: { type: String, default: "nil" },
  more_olevel_1: { type: String },

  es_school: { type: String, default: "nil" },
  es_country: { type: String, default: "nil" },
  es_address: { type: String, default: "nil" },
  es_date_start: { type: String, default: "nil" },
  es_date_end: { type: String, default: "nil" },
  es_certificate: { type: String, default: "nil" },
  es_date_c: { type: String, default: "nil" },
  es_grade_award: { type: String, default: "nil" },
  es_other: { type: String, default: "nil" },

  es_school_other: { type: String, default: "nil" },
  es_country_other: { type: String, default: "nil" },
  es_address_other: { type: String, default: "nil" },
  es_date_start_other: { type: String, default: "nil" },
  es_date_end_other: { type: String, default: "nil" },
  es_certificate_other: { type: String, default: "nil" },
  es_date_c_other: { type: String, default: "nil" },
  es_grade_award_other: { type: String, default: "nil" },
  es_other_other: { type: String, default: "nil" },

  ts_school: { type: String, default: "nil" },
  ts_country: { type: String, default: "nil" },
  ts_address: { type: String, default: "nil" },
  ts_date_start: { type: String, default: "nil" },
  ts_date_end: { type: String, default: "nil" },
  ts_certificate: { type: String, default: "nil" },
  ts_date_c: { type: String, default: "nil" },
  ts_grade_award: { type: String, default: "nil" },
  ts_other: { type: String, default: "nil" },
  additional_undergrad_1: { type: String },

  ts_school_other: { type: String, default: "nil" },
  ts_country_other: { type: String, default: "nil" },
  ts_address_other: { type: String, default: "nil" },
  ts_date_start_other: { type: String, default: "nil" },
  ts_date_end_other: { type: String, default: "nil" },
  ts_certificate_other: { type: String, default: "nil" },
  ts_date_c_other: { type: String, default: "nil" },
  ts_grade_award_other: { type: String, default: "nil" },
  ts_other_other: { type: String, default: "nil" },
  additional_undergrad_2: { type: String },

  tss_school_other: { type: String, default: "nil" },
  tss_country_other: { type: String, default: "nil" },
  tss_address_other: { type: String, default: "nil" },
  tss_date_start_other: { type: String, default: "nil" },
  tss_date_end_other: { type: String, default: "nil" },
  tss_certificate_other: { type: String, default: "nil" },
  tss_date_c_other: { type: String, default: "nil" },
  tss_grade_award_other: { type: String, default: "nil" },
  tss_other_other: { type: String, default: "nil" },

  deported: { type: String, default: "nil" },
  deported_reason: { type: String, default: "nil" },

  r_fullname_1: { type: String, default: "nil" },
  r_email_1: { type: String, default: "nil" },
  r_phone_1: { type: String, default: "nil" },
  r_employer_1: { type: String, default: "nil" },
  r_address_1: { type: String, default: "nil" },
  r_rank_1: { type: String, default: "nil" },

  r_fullname_2: { type: String, default: "nil" },
  r_email_2: { type: String, default: "nil" },
  r_phone_2: { type: String, default: "nil" },
  r_employer_2: { type: String, default: "nil" },
  r_address_2: { type: String, default: "nil" },
  r_rank_2: { type: String, default: "nil" },

  r_fullname_3: { type: String, default: "nil" },
  r_email_3: { type: String, default: "nil" },
  r_phone_3: { type: String, default: "nil" },
  r_employer_3: { type: String, default: "nil" },
  r_address_3: { type: String, default: "nil" },
  r_rank_3: { type: String, default: "nil" },

  cv_resume: { type: String, default: defaultImageURL },
  passport: { type: String, default: defaultImageURL },
  international_passport: { type: String, default: defaultImageURL },

  secondary_certificate: { type: String, default: defaultImageURL },
  undergraduate_certificate: { type: String, default: defaultImageURL },
  graduate_certificate: { type: String, default: defaultImageURL },
  post_certificate: { type: String, default: defaultImageURL },
  professional_certificate: { type: String, default: defaultImageURL },
  personal_statement: { type: String, default: defaultImageURL },
});

const Application = mongoose.model("Application", ApplicationSchema);

module.exports = Application;
